### ISSUE TITLE
Retrieving public posts error

### ISSUE THREAD

**Issue by robinpx** [Harrilee/PigeonSale#2]
There is an sql error retrieving public posts, shuts down server and connection is lost. 
<img width="801" alt="Screen Shot 2021-11-14 at 3 02 09 PM" src="https://user-images.githubusercontent.com/24725728/141671018-6612980f-1cbf-47e1-80c3-be564bb6078b.png">

**Comment by Harrilee** [comment]
The MySQL server is reset. The problem might work fine now.

**Comment by robinpx** [comment]
Additional problem: no posts retrieved despite posts in database.

**Comment by robinpx** [comment]
> There is an sql error retrieving public posts, shuts down server and connection is lost. <img alt="Screen Shot 2021-11-14 at 3 02 09 PM" width="801" src="https://user-images.githubusercontent.com/24725728/141671018-6612980f-1cbf-47e1-80c3-be564bb6078b.png">

Issue resolved by creating sequential response (if profile loaded, then load posts)

**Comment by Harrilee** [comment]
> Additional problem: no posts retrieved despite posts in database.

This is due to those posts are marked deleted. I have added a verification section of the `post_status` field. For frontend, `post_status` should be 1 for public, 2 for delete, and other numbers (including 0) is not allowed.

**Comment by robinpx** [comment]
Tested, new error 
<img width="797" alt="Screen Shot 2021-11-18 at 7 20 28 PM" src="https://user-images.githubusercontent.com/24725728/142406144-b85551b1-6bb5-4718-9d27-f19caa4b350a.png">

**Comment by Harrilee** [comment]
This is due to the legacy version of `flask.json`. Try `pip3 install --upgrade flask`
