### ISSUE TITLE
Change Password Error

### ISSUE THREAD

**Issue by robinpx** [Harrilee/PigeonSale#4]
I changed the password to one of my accounts, but now I can't log back in. 
<img width="1045" alt="Screen Shot 2021-11-19 at 4 58 31 PM" src="https://user-images.githubusercontent.com/24725728/142595075-98cf44dd-9f90-41c9-aaca-9552d8799af4.png">

**Comment by Harrilee** [comment]
The problem is solved. I used the wrong variable.

See https://github.com/Harrilee/PigeonSale/commit/8ec7a523f580e11d6e892dd0740e354c2056f51c
