### ISSUE TITLE
Uploading Private Posts Not Working

### ISSUE THREAD

**Issue by robinpx** [Harrilee/PigeonSale#5]
Error loading private posts despite correct values.
<img width="769" alt="Screen Shot 2021-11-21 at 8 35 46 PM" src="https://user-images.githubusercontent.com/24725728/142762068-45a776e2-989e-460f-973b-6e3f34969d9f.png">

**Comment by Harrilee** [comment]
It is fixed. The problem is caused by `post_status` checking - I typed the wrong status allowed. See https://github.com/Harrilee/PigeonSale/commit/3450ff020dc666de92da2a4918ca96fc71a9124b
